CREATE TABLE vendors (
  vendor_id SERIAL PRIMARY KEY,
  vendor_slug VARCHAR(100) NOT NULL UNIQUE CHECK(LENGTH(TRIM(vendor_slug)) >= 4),
  email VARCHAR(100) NOT NULL UNIQUE CHECK(LENGTH(TRIM(email)) >= 4),
  fullname VARCHAR(40) NOT NULL CHECK(LENGTH(TRIM(fullname)) >= 4),
  hash_password VARCHAR(150) NOT NULL,
  is_premium BOOLEAN  NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  product_id SERIAL PRIMARY KEY,
  vendor_id INTEGER,
  title VARCHAR(120) NOT NULL CHECK(LENGTH(TRIM(title)) >= 4),
  price NUMERIC NOT NULL DEFAULT 1, 
  description TEXT NOT NULL CHECK(LENGTH(TRIM(description)) >= 10),
  image TEXT CHECK(LENGTH(TRIM(image)) >= 5),
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_to_vendors FOREIGN KEY(vendor_id) REFERENCES vendors(vendor_id)
);